language: python
python: 3.6
script: python setup.py test
deploy:
  provider: pypi
  user: seehait
  password:
    secure: NzbBwzhRIkQifKgb52gyKtwliXMYKbeMSRFG9tlLqMxfcp6QfbrJPqC0zmbj5mgvQMUNuhppJKXTnh4kZzW54huK6yZgs0SHCs3KZ0yY6FTHrjHfW2Niw/Zvr4mI++fl92ldL9ms3xMVbXVU3k5aBLJuJZLxotCvJxY4DML/IZT5aqdIHpArjsNQm7ZOC+IzC5IDG10fsC68oGeUYcibRM72l191lM1kmrc+MvyK7MrnVuNan9cNywVOaqy1ePrRi7jsQb20Wd9PlREhXzOw47OxlEzkLYUDd+K/zJVmOfcBTdCAc5B/jHG4C8qB/ZOCBWRZuNWqYsyXnJiyEbfaPoU19v1C5olWOaIk1V07ZV8v6mF5ZyWSTeVPvGGysLd/920r4YPM05+evPoHYEoHFGIsDQW8GikxrQiGMx5ClQzpxr2OQ/11mRB0DwFHSWM+IOwlPR4wr8tCz5XH5Fx2cZW7T1R8FIRNAsOJFZ2NNg0QBifS+i2kTnoxcIsKbKy7aKFosbucV6YkVlgMfT9/h/VNHXkjAlHpGymnNh9wk17m2nL5iSlYf+FyFcLkdjBvumGs5AR9e+H+Fo9qlXs8NLaVMas7fN5/dvQQx6cdPN1fjJNmALTcf1Scxn5Utv+8AmoALjwQKTXpEXrri4UVMGJZjkUEUUU4S5Yt6WdqyRg=
  on:
    tags: true
    python: 3.6
  distributions: sdist bdist_wheel
