language: python
python: 3.6
script: python setup.py test
deploy:
  provider: pypi
  user: __token__
  password:
    secure: hSE2Nolxnwk4XrhE1aHz+r7ILUI27TW28v8To+FoZ8oXj0ylk5gtfdZBueND5FKV9kwf6KNUnhOUHTuvzarZ9hFOWmHipXWsqr+XnVkzrOZAmM8THNRUZAkPuNlNdTICwR8dmLfxP6yKGjUHrfN7ScE+11h+QWGklO61N7viFYBSA9Bu6O+5sEdX1hmEwwb2+FrSftlFZyzY4LGLuqWVwl7aemwpfcD/VQ7USvJ2PuxPXUdAPJr3wpkij9cKCXnLcLNAP8NbAPc8xBCQ+Ao8tRre9L4TC5qAoks9bnMXaCNfepOJrOCog2kF0pquRiuV3SNIVu9KKoSwXD9YsOFMAViEy9g7Kti/Z5s40bUf8kpKYxeUN6D25RwAihw6ViV6fWzmxJteVNre3lfcYxskB/XIWt0yLe3yn92U0MNf7WEwU+91JSOYFNBKIe+UyS8pzqYMEUuSTeZVKXb7V77ddyUveaEUAO5Jhp7Lino4A56A/ib8FEgTosr1g2PkAc3xpTIndMr6YEO6kicZ4NDCm+gnO4vuz/O2TAypWo7I/cv9mw4HULM4vGNR9cKkdCianVoOUEMReef9or8FLyWdLqNRHzQ3CD3rTrNg/3o7GFU8nzgQtk1YnmGIJ0Fbjv5krmoKc7k27ROgQ56vyVoQ0prMPpxuiFMUUAbvArnbyPI=
  on:
    tags: true
    python: 3.6
  distributions: sdist bdist_wheel
